#  minPercentPlayers: 50	//The percentage of a full lobby, before players in queue are teleported and before a game will start.
#  preGameTimer: 20			//The countdown time before the game starts once the minimum number of players are in the game.
#  resetPreGameTimerOnJoin: true	//If set to true, the pregame timer will reset whenver a new player joins a game.
#  resetPreGameTimerThreshold: 80	//This is the threshold based on the percentage of players in a game. If the number of players in the game is higher than the threshold, the timer will not restart. 
#  timeAfterGame: 10	//This is the amount of time after the end of a game, before the game shutsdown/restarts.
#  maxMapSize: 200		//This is the maximum square size of the map. 
points:
  pointsPerKill: 1
  vipMultiplier: 2
  svipMultiplier: 3
  eliteMultiplier: 4
  rubyMultiplier: 5
spawn:
  world: kitpvpmapa
  x: 0
  y: 166
  z: 28
  yaw: 270
  pitch: 0
allowed:
  - "obed_007"
  - "Ranzoot"
  - "T_I_G_R_E"
  - "Polar11bearYT"
permissions:
  default:
    - "tournament.join"
    - "tournament.leave"
    - "nocheatplus.command.info"
    - "smartournament.default"
  YOUTUBER:
    - "yt.promo"
  VIP:
    - ""
  SVIP:
    - ""
  ELITE:
    - ""
  RUBY:
    - ""
  HELPER:
    - "nocheatplus.command.*"
    - "staff.staffchat"
    - "staff.freeze"
    - "staff.report"
    - "staff.gui"
    - "staff.member"
    - "staff.alerts.mention"
    - "staff.chat.clear"
  MOD:
    - "tournament.create"
    - "tournament.start"
    - "tournament.forcestart"
    - "tournament.end"
    - "rachas.set"
    - "staff.*"
    - "SUMO.START"
    - "SUMO.END"
    - "invrestore.command"
    - "smarttournament.start"
    - "smarttournament.end"
    - "smarttournament.chatbypass"
    - "ss.node"
  ADMIN:
    - "tournament.create"
    - "tournament.start"
    - "tournament.forcestart"
    - "tournament.end"
    - "SUMO.*"
    - "announcer.*"
  OWNER:
    - ""
